name: build-dotnet
on:
  push:
    paths:
      - 'src/pipeline-status/**'
      - '.github/workflows/build-dotnet.yml'
  pull_request:
    paths:
      - 'src/pipeline-status/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore src/pipeline-status/pipeline-status.csproj
      - run: dotnet build src/pipeline-status/pipeline-status.csproj -c Release --no-restore
      - run: dotnet publish src/pipeline-status/pipeline-status.csproj -c Release -o out
